import type { BoxDef, LayoutDef } from './layout.js';

/**
 * Mob layouts beyond the first ones in layout.ts: each verified against the Java model code
 * (texOffs and addBox) and the vanilla textures of 1.21.1, 1.21.5 and 1.21.11, by running the
 * vanilla texture through the views. Same conventions as layout.ts.
 */

// ---- Small animals --------------------------------------------------------------------------


const SMALL_ANIMALS: LayoutDef[] = [
  {
    id: 'fox',
    title: 'Fox (48×32)',
    texture: 'entity/fox/fox',
    size: [48, 32],
    parts: {
      head: { box: [8, 6, 6], uv: [1, 5] },
      rightEar: { box: [2, 2, 1], uv: [8, 1] },
      leftEar: { box: [2, 2, 1], uv: [15, 1] },
      snout: { box: [4, 2, 3], uv: [6, 18] },
      body: { box: [6, 11, 6], uv: [24, 15], turned: true },
      tail: { box: [4, 9, 5], uv: [30, 0], turned: true },
      rightLeg: { box: [2, 6, 2], uv: [13, 24] },
      leftLeg: { box: [2, 6, 2], uv: [4, 24] },
    },
    groups: { ears: ['rightEar', 'leftEar'], legs: ['rightLeg', 'leftLeg'] },
    boxes: [
      { part: 'head', at: [-4, 14.5, -8] },
      { part: 'rightEar', at: [-4, 12.5, -7] },
      { part: 'leftEar', at: [2, 12.5, -7] },
      { part: 'snout', at: [-2, 18.5, -11] },
      { part: 'rightLeg', at: [-3, 18, 6] },
      { part: 'leftLeg', at: [1, 18, 6] },
      { part: 'rightLeg', at: [-3, 18, -1] },
      { part: 'leftLeg', at: [1, 18, -1] },
      { part: 'body', at: [-3, 13.5, -2] },
      { part: 'tail', at: [-2, 13, 9] },
    ],
    opaque: true,
    usedBy: [
      'textures/entity/fox/fox.png',
      'snow_fox.png',
      'fox_sleep.png and snow_fox_sleep.png (the same fox with its eyes closed, shown while it sleeps)',
    ],
    note: 'The body and the bushy tail lie along the fox: their top is its back, and the tail points straight back from the rump (in game it droops 3°). The snout sits on the bottom two rows of head.front. Both right legs share one texture, and both left legs another. The head sits half a pixel off the grid; the views snap it.',
  },
  {
    id: 'rabbit',
    title: 'Rabbit (64×32)',
    texture: 'entity/rabbit/brown',
    size: [64, 32],
    parts: {
      head: { box: [5, 4, 5], uv: [32, 0] },
      nose: { box: [1, 1, 1], uv: [32, 9] },
      rightEar: { box: [2, 5, 1], uv: [52, 0] },
      leftEar: { box: [2, 5, 1], uv: [58, 0] },
      body: { box: [6, 5, 10], uv: [0, 0] },
      tail: { box: [3, 3, 2], uv: [52, 6] },
      rightFrontLeg: { box: [2, 7, 2], uv: [0, 15] },
      leftFrontLeg: { box: [2, 7, 2], uv: [8, 15] },
      rightHaunch: { box: [2, 4, 5], uv: [16, 15] },
      leftHaunch: { box: [2, 4, 5], uv: [30, 15] },
      rightHindFoot: { box: [2, 1, 7], uv: [8, 24] },
      leftHindFoot: { box: [2, 1, 7], uv: [26, 24] },
    },
    groups: {
      ears: ['rightEar', 'leftEar'],
      legs: ['rightFrontLeg', 'leftFrontLeg', 'rightHaunch', 'leftHaunch', 'rightHindFoot', 'leftHindFoot'],
      haunches: ['rightHaunch', 'leftHaunch'],
      feet: ['rightHindFoot', 'leftHindFoot'],
    },
    boxes: [
      { part: 'head', at: [-2.5, 12, -6] },
      { part: 'nose', at: [-0.5, 13.5, -6.5] },
      { part: 'rightEar', at: [-2.5, 7, -2] },
      { part: 'leftEar', at: [0.5, 7, -2] },
      { part: 'body', at: [-3, 17, -2] },
      { part: 'tail', at: [-1.5, 18.5, 7] },
      { part: 'rightFrontLeg', at: [-4, 17, -2] },
      { part: 'leftFrontLeg', at: [2, 17, -2] },
      { part: 'rightHaunch', at: [-4, 17.5, 3.7] },
      { part: 'leftHaunch', at: [2, 17.5, 3.7] },
      { part: 'rightHindFoot', at: [-4, 23, 0] },
      { part: 'leftHindFoot', at: [2, 23, 0] },
    ],
    opaque: true,
    usedBy: [
      'textures/entity/rabbit/brown.png, white.png, black.png, gold.png, salt.png, white_splotched.png, toast.png',
      'caerbannog.png (the killer bunny)',
    ],
    note: 'Every leg piece has its own texture: front legs, haunches (the thighs) and long hind feet that lie flat on the ground. The nose is a 1-pixel box on head.front, a row below the middle. In game the body leans 20° nose down, the haunches, front legs and tail lean too, and the ears splay 15° apart; the views show them straight. The adult model is drawn at 0.6 scale, which does not change the texture. The UVs are the same in 1.21.1, 1.21.5 and 1.21.11.',
  },
  {
    id: 'bee',
    title: 'Bee (64×64)',
    texture: 'entity/bee/bee',
    size: [64, 64],
    parts: {
      body: { box: [7, 7, 10], uv: [0, 0] },
      rightAntenna: { box: [1, 2, 3], uv: [2, 3], cutout: true, shared: true },
      leftAntenna: { box: [1, 2, 3], uv: [2, 0], cutout: true, shared: true },
      stinger: { box: [0, 1, 2], uv: [26, 7], cutout: true },
      wing: { box: [9, 0, 6], uv: [0, 18], cutout: true },
      frontLegs: { box: [7, 2, 0], uv: [26, 1], cutout: true },
      middleLegs: { box: [7, 2, 0], uv: [26, 3], cutout: true },
      backLegs: { box: [7, 2, 0], uv: [26, 5], cutout: true },
    },
    groups: { antennae: ['rightAntenna', 'leftAntenna'], legs: ['frontLegs', 'middleLegs', 'backLegs'] },
    boxes: [
      { part: 'body', at: [-3.5, 15, -5] },
      { part: 'rightAntenna', at: [-2.5, 15, -8] },
      { part: 'leftAntenna', at: [1.5, 15, -8] },
      { part: 'stinger', at: [0, 18, 5] },
      { part: 'wing', at: [-10.5, 15, -3] },
      { part: 'wing', at: [1.5, 15, -3], mirror: true },
      { part: 'frontLegs', at: [-3.5, 22, -2] },
      { part: 'middleLegs', at: [-3.5, 22, 0] },
      { part: 'backLegs', at: [-3.5, 22, 2] },
    ],
    opaque: true,
    usedBy: [
      'textures/entity/bee/bee.png',
      'bee_angry.png, bee_nectar.png, bee_angry_nectar.png (the same layout: red eyes, pollen on the body)',
    ],
    note: 'The wings are flat planes with no height that lie on the back: only wing.top and wing.bottom have pixels, they show in the top view and close-ups, not from the sides, and the left wing is the right one mirrored. Vanilla paints only wing.top and leaves a stray copy of the wing below it that the game never reads; the game draws the wings from both sides. Each set of legs is a flat strip under the body (front only), and the stinger is a fin with only .right and .left faces; vanilla paints only its right face. The antennae are thin sticks painted on their inner side, and their texture boxes overlap by 4 pixels in vanilla (rightAntenna.top and .bottom read leftAntenna.front and .left), so keep those pixels transparent. In game the wings flap and splay 15°; the views show them flat. bee_stinger.png is the stinger stuck in a player, a separate 16×16 texture.',
  },
  {
    id: 'parrot',
    title: 'Parrot (32×32)',
    texture: 'entity/parrot/parrot_red_blue',
    size: [32, 32],
    parts: {
      head: { box: [2, 3, 2], uv: [2, 2] },
      headTop: { box: [2, 1, 4], uv: [10, 0] },
      beak: { box: [1, 2, 1], uv: [11, 7] },
      beakTip: { box: [1, 2, 1], uv: [16, 7] },
      feather: { box: [0, 5, 4], uv: [2, 18], cutout: true },
      body: { box: [3, 6, 3], uv: [2, 8] },
      wing: { box: [1, 5, 3], uv: [19, 8] },
      tail: { box: [3, 4, 1], uv: [22, 1] },
      leg: { box: [1, 2, 1], uv: [14, 18], cutout: true },
    },
    groups: { beaks: ['beak', 'beakTip'], wings: ['wing'], legs: ['leg'] },
    boxes: [
      { part: 'head', at: [-1, 14.19, -3.76] },
      { part: 'headTop', at: [-1, 13.19, -5.76] },
      { part: 'beak', at: [-0.5, 14.19, -4.76] },
      { part: 'beakTip', at: [-0.5, 13.94, -5.71] },
      { part: 'feather', at: [0, 9.54, -4.61] },
      { part: 'body', at: [-1.5, 16.5, -4.5] },
      { part: 'wing', at: [-2, 16.94, -4.26] },
      { part: 'wing', at: [1, 16.94, -4.26] },
      { part: 'tail', at: [-1.5, 20.07, 0.16] },
      { part: 'leg', at: [-1.5, 22, -1.55] },
      { part: 'leg', at: [0.5, 22, -1.55] },
    ],
    opaque: true,
    usedBy: ['textures/entity/parrot/parrot_red_blue.png, parrot_blue.png, parrot_green.png, parrot_yellow_blue.png, parrot_grey.png'],
    note: 'A tiny bird: headTop is a slab over the head that juts forward over the beak, the beak hangs from head.front and beakTip is the hooked upper tip in front of it. The feather is a crest seen from the sides (.right and .left only). Both wings share one texture, and so do both legs. In game the body leans forward 28°, the tail 58°, the wings swing back 40° and are turned around (each wing\'s outside is its .left face on the right wing and its .right face on the left wing); the views show them straight and unturned. The vanilla files fill the unused space with an opaque background color.',
  },
  {
    id: 'axolotl',
    title: 'Axolotl (64×64)',
    texture: 'entity/axolotl/axolotl_lucy',
    size: [64, 64],
    parts: {
      head: { box: [8, 5, 5], uv: [0, 1] },
      gills: { box: [8, 3, 0], uv: [3, 37], cutout: true },
      rightGills: { box: [3, 7, 0], uv: [0, 40], cutout: true },
      leftGills: { box: [3, 7, 0], uv: [11, 40], cutout: true },
      body: { box: [8, 4, 10], uv: [0, 11] },
      fin: { box: [0, 5, 9], uv: [2, 17], cutout: true },
      tail: { box: [0, 5, 12], uv: [2, 19], cutout: true },
      leg: { box: [3, 5, 0], uv: [2, 13], cutout: true },
      legBack: { box: [3, 5, 0], uv: [5, 13], cutout: true },
    },
    groups: { allGills: ['gills', 'rightGills', 'leftGills'], legs: ['leg', 'legBack'] },
    boxes: [
      { part: 'body', at: [-4, 18, -4] },
      { part: 'fin', at: [0, 17, -3] },
      { part: 'head', at: [-4, 17, -9] },
      { part: 'gills', at: [-4, 14, -5] },
      { part: 'rightGills', at: [-7, 15, -5] },
      { part: 'leftGills', at: [4, 15, -5] },
      { part: 'leg', at: [-5.5, 21, 4] },
      { part: 'leg', at: [2.5, 21, 4] },
      { part: 'leg', at: [-5.5, 21, -3] },
      { part: 'leg', at: [2.5, 21, -3] },
      { part: 'tail', at: [0, 17, 6] },
    ],
    opaque: true,
    usedBy: ['textures/entity/axolotl/axolotl_lucy.png, axolotl_wild.png, axolotl_gold.png, axolotl_cyan.png, axolotl_blue.png'],
    note: 'Only the top 48 rows are used. The gills are three flat fronds behind the head: gills on top, rightGills and leftGills on the sides (Java calls them the other way round). The fin along the back and the tail are fins seen from the sides; vanilla paints only their .right face and the game shows it from both sides. The four legs share one flat texture, leg, whose back side is legBack (not drawn in the views). The views show the legs hanging straight down under the body; in game they splay out and paddle.',
  },
  {
    id: 'frog',
    title: 'Frog (48×48)',
    texture: 'entity/frog/temperate_frog',
    size: [48, 48],
    parts: {
      head: { box: [7, 3, 9], uv: [0, 13] },
      upperMouth: { box: [7, 0, 9], uv: [23, 13], cutout: true },
      rightEye: { box: [3, 2, 3], uv: [0, 0] },
      leftEye: { box: [3, 2, 3], uv: [0, 5] },
      body: { box: [7, 3, 9], uv: [3, 1] },
      lowerMouth: { box: [7, 0, 9], uv: [23, 22], cutout: true },
      tongue: { box: [4, 0, 7], uv: [17, 13], cutout: true },
      vocalSac: { box: [7, 2, 3], uv: [26, 5] },
      rightArm: { box: [2, 3, 3], uv: [0, 38] },
      leftArm: { box: [2, 3, 3], uv: [0, 32] },
      rightHand: { box: [8, 0, 8], uv: [2, 40], cutout: true },
      leftHand: { box: [8, 0, 8], uv: [18, 40], cutout: true },
      rightLeg: { box: [3, 3, 4], uv: [0, 25] },
      leftLeg: { box: [3, 3, 4], uv: [14, 25] },
      rightFoot: { box: [8, 0, 8], uv: [18, 32], cutout: true },
      leftFoot: { box: [8, 0, 8], uv: [2, 32], cutout: true },
    },
    groups: {
      eyes: ['rightEye', 'leftEye'],
      mouth: ['upperMouth', 'lowerMouth', 'tongue'],
      arms: ['rightArm', 'leftArm'],
      legs: ['rightLeg', 'leftLeg'],
      hands: ['rightHand', 'leftHand'],
      feet: ['rightFoot', 'leftFoot'],
    },
    boxes: [
      // The vocal sac first: it sits inside the body, which wins where they meet.
      { part: 'vocalSac', at: [-3.5, 20.9, -3.9] },
      { part: 'body', at: [-3.5, 20, -4] },
      { part: 'lowerMouth', at: [-3.5, 21, -4] },
      { part: 'tongue', at: [-2, 21, -2.1] },
      { part: 'head', at: [-3.5, 18, -4] },
      { part: 'upperMouth', at: [-3.5, 19, -4] },
      { part: 'rightEye', at: [-3.5, 16, -3] },
      { part: 'leftEye', at: [0.5, 16, -3] },
      { part: 'rightArm', at: [-5, 21, -3.5] },
      { part: 'leftArm', at: [3, 21, -3.5] },
      { part: 'rightHand', at: [-8, 24, -7.5] },
      { part: 'leftHand', at: [0, 24, -7.5] },
      { part: 'rightLeg', at: [-5.5, 21, 2] },
      { part: 'leftLeg', at: [2.5, 21, 2] },
      { part: 'rightFoot', at: [-9.5, 24, 0] },
      { part: 'leftFoot', at: [1.5, 24, 0] },
    ],
    opaque: true,
    usedBy: ['textures/entity/frog/temperate_frog.png, warm_frog.png, cold_frog.png'],
    note: 'The head is the upper jaw and the body the lower one; they overlap by a row, so the head\'s bottom row and the body\'s top hide inside. The mouth is two flat planes with no height inside the jaws, upperMouth and lowerMouth, plus the tongue; they show when the frog opens its mouth, and vanilla paints only their .top faces. The vocalSac is the throat that puffs out when the frog croaks. The hands and feet are flat webbed planes on the ground (only .top and .bottom have pixels; vanilla paints the top); they show in close-ups, not from the sides.',
  },
  {
    id: 'turtle',
    title: 'Sea turtle (128×64)',
    texture: 'entity/turtle/big_sea_turtle',
    size: [128, 64],
    parts: {
      head: { box: [6, 5, 6], uv: [3, 0] },
      shell: { box: [19, 20, 6], uv: [7, 37], turned: true },
      belly: { box: [11, 18, 3], uv: [31, 1], turned: true },
      eggBelly: { box: [9, 18, 1], uv: [70, 33], turned: true },
      rightFrontLeg: { box: [13, 1, 5], uv: [27, 30] },
      leftFrontLeg: { box: [13, 1, 5], uv: [27, 24] },
      rightHindLeg: { box: [4, 1, 10], uv: [1, 23] },
      leftHindLeg: { box: [4, 1, 10], uv: [1, 12] },
    },
    groups: { flippers: ['rightFrontLeg', 'leftFrontLeg', 'rightHindLeg', 'leftHindLeg'], legs: ['rightFrontLeg', 'leftFrontLeg', 'rightHindLeg', 'leftHindLeg'] },
    boxes: [
      { part: 'head', at: [-3, 18, -13] },
      { part: 'shell', at: [-9.5, 15, -7] },
      { part: 'belly', at: [-5.5, 21, -7] },
      { part: 'eggBelly', at: [-4.5, 24, -7] },
      { part: 'rightFrontLeg', at: [-18, 21, -6] },
      { part: 'leftFrontLeg', at: [5, 21, -6] },
      { part: 'rightHindLeg', at: [-5.5, 22, 11] },
      { part: 'leftHindLeg', at: [1.5, 22, 11] },
    ],
    opaque: true,
    usedBy: ['textures/entity/turtle/big_sea_turtle.png'],
    note: 'The shell and the belly under it lie along the turtle: shell.top is the top of the shell, shell.front faces the head. eggBelly is a bulge under the belly that only shows while a turtle carries eggs. The flippers are flat slabs one pixel thick: the front ones stick out sideways, the hind ones trail behind.',
  },
  {
    id: 'armadillo',
    title: 'Armadillo (64×64)',
    texture: 'entity/armadillo',
    size: [64, 64],
    parts: {
      body: { box: [8, 8, 12], uv: [0, 40], overlay: [0, 20] },
      head: { box: [3, 5, 2], uv: [43, 15] },
      rightEar: { box: [2, 5, 0], uv: [43, 10], cutout: true },
      leftEar: { box: [2, 5, 0], uv: [47, 10], cutout: true },
      tail: { box: [1, 6, 1], uv: [44, 53] },
      rightFrontLeg: { box: [2, 3, 2], uv: [51, 43] },
      leftFrontLeg: { box: [2, 3, 2], uv: [42, 43] },
      rightHindLeg: { box: [2, 3, 2], uv: [51, 31] },
      leftHindLeg: { box: [2, 3, 2], uv: [42, 31] },
      ball: { box: [10, 10, 10], uv: [0, 0] },
    },
    groups: { ears: ['rightEar', 'leftEar'], legs: ['rightFrontLeg', 'leftFrontLeg', 'rightHindLeg', 'leftHindLeg'] },
    boxes: [
      { part: 'body', at: [-4, 14, -6] },
      { part: 'head', at: [-1.5, 18, -8] },
      { part: 'rightEar', at: [-3.5, 15, -7.6] },
      { part: 'leftEar', at: [1.5, 15, -7.6] },
      { part: 'tail', at: [-0.5, 17.91, 5.09] },
      { part: 'rightFrontLeg', at: [-3, 21, -5] },
      { part: 'leftFrontLeg', at: [1, 21, -5] },
      { part: 'rightHindLeg', at: [-3, 21, 3] },
      { part: 'leftHindLeg', at: [1, 21, 3] },
    ],
    opaque: true,
    usedBy: ['textures/entity/armadillo.png'],
    note: 'body is the soft body and body@overlay the shell over it, drawn slightly larger: its bottom is open and its sides have gaps for the legs and head, so leave those transparent. ball is the armadillo rolled up when scared, a 10×10×10 cube shown instead of everything else; it has no place in the views. The ears are flat (front only). In game the head tilts 22° down, the tail 29° and the ears splay; the views show them straight.',
  },
  {
    id: 'bat',
    title: 'Bat (32×32)',
    texture: 'entity/bat',
    size: [32, 32],
    parts: {
      head: { box: [4, 3, 2], uv: [0, 7] },
      rightEar: { box: [3, 5, 0], uv: [1, 15], cutout: true },
      leftEar: { box: [3, 5, 0], uv: [8, 15], cutout: true },
      body: { box: [3, 5, 2], uv: [0, 0] },
      rightWing: { box: [2, 7, 0], uv: [12, 0], cutout: true },
      rightWingTip: { box: [6, 8, 0], uv: [16, 0], cutout: true },
      leftWing: { box: [2, 7, 0], uv: [12, 7], cutout: true },
      leftWingTip: { box: [6, 8, 0], uv: [16, 8], cutout: true },
      feet: { box: [3, 2, 0], uv: [16, 16], cutout: true },
      rightEarBack: { box: [3, 5, 0], uv: [4, 15], cutout: true },
      leftEarBack: { box: [3, 5, 0], uv: [11, 15], cutout: true },
      rightWingBack: { box: [2, 7, 0], uv: [14, 0], cutout: true },
      rightWingTipBack: { box: [6, 8, 0], uv: [22, 0], cutout: true },
      leftWingBack: { box: [2, 7, 0], uv: [14, 7], cutout: true },
      leftWingTipBack: { box: [6, 8, 0], uv: [22, 8], cutout: true },
      feetBack: { box: [3, 2, 0], uv: [19, 16], cutout: true },
    },
    groups: {
      ears: ['rightEar', 'leftEar', 'rightEarBack', 'leftEarBack'],
      wings: ['rightWing', 'rightWingTip', 'leftWing', 'leftWingTip', 'rightWingBack', 'rightWingTipBack', 'leftWingBack', 'leftWingTipBack'],
      backs: ['rightEarBack', 'leftEarBack', 'rightWingBack', 'rightWingTipBack', 'leftWingBack', 'leftWingTipBack', 'feetBack'],
    },
    boxes: [
      { part: 'rightEar', at: [-4, 11, 0] },
      { part: 'leftEar', at: [1, 11, 0] },
      { part: 'head', at: [-2, 14, -1] },
      { part: 'rightWingTip', at: [-9.5, 15, 0] },
      { part: 'rightWing', at: [-3.5, 15, 0] },
      { part: 'leftWing', at: [1.5, 15, 0] },
      { part: 'leftWingTip', at: [3.5, 15, 0] },
      { part: 'feet', at: [-1.5, 22, 0] },
      { part: 'body', at: [-1.5, 17, -1] },
    ],
    opaque: true,
    usedBy: ['textures/entity/bat.png (the bat model of 1.20.3 and later)'],
    note: 'The ears, the wings (an inner piece and a tip on each side) and the feet are flat planes through the middle of the body. Each has a painted back: the parts ending in Back are the same planes seen from behind (drawn mirrored, so the left edge of a Back face is the right edge of its front), and the views only show the fronts. In game the bat hangs upside down at rest and flaps with its wings folded or spread; the views show it upright with the wings spread flat.',
  },
];

const SMALL_ANIMALS_ALIASES: Record<string, string> = {
  snow_fox: 'fox',
  fox_sleep: 'fox',
  killer_bunny: 'rabbit',
  caerbannog: 'rabbit',
  angry_bee: 'bee',
  temperate_frog: 'frog',
  warm_frog: 'frog',
  cold_frog: 'frog',
  sea_turtle: 'turtle',
  big_sea_turtle: 'turtle',
};

// ---- Horses and large animals ---------------------------------------------------------------


const HORSE_LEGS: BoxDef[] = [
  { part: 'leg', at: [-5, 13, 6] },
  { part: 'leg', at: [1, 13, 6], mirror: true },
  { part: 'leg', at: [-5, 13, -12] },
  { part: 'leg', at: [1, 13, -12], mirror: true },
];

const LARGE_ANIMALS: LayoutDef[] = [
  {
    id: 'horse',
    title: 'Horse (64×64)',
    texture: 'entity/horse/horse_brown',
    size: [64, 64],
    parts: {
      head: { box: [6, 5, 7], uv: [0, 13] },
      muzzle: { box: [4, 5, 5], uv: [0, 25] },
      ear: { box: [2, 3, 1], uv: [19, 16] },
      neck: { box: [4, 12, 7], uv: [0, 35] },
      mane: { box: [2, 16, 2], uv: [56, 36] },
      body: { box: [10, 10, 22], uv: [0, 32] },
      tail: { box: [3, 14, 4], uv: [42, 36] },
      leg: { box: [4, 11, 4], uv: [48, 21] },
    },
    groups: { legs: ['leg'] },
    boxes: [
      { part: 'head', at: [-3, -7, -14] },
      { part: 'muzzle', at: [-2, -7, -19] },
      { part: 'ear', at: [-2.55, -9, -8] },
      { part: 'ear', at: [0.55, -9, -8] },
      { part: 'neck', at: [-2, -2, -14] },
      { part: 'mane', at: [-1, -7, -7] },
      { part: 'body', at: [-5, 3, -12] },
      { part: 'tail', at: [-1.5, 6, 7] },
      ...HORSE_LEGS,
    ],
    opaque: true,
    usedBy: [
      'textures/entity/horse/horse_{white,creamy,chestnut,brown,black,gray,darkbrown}.png',
      'horse_markings_{white,whitefield,whitedots,blackdots}.png (markings over the coat, same layout, transparent elsewhere)',
      'horse_zombie.png and horse_skeleton.png (zombie and skeleton horses)',
      'textures/entity/equipment/horse_body/*.png (horse armor: leather, copper, iron, gold, diamond, netherite, leather_overlay; drawn slightly larger, transparent where the coat shows)',
    ],
    note: 'The body is a plain box along the horse (body.front is its chest, body.back its rump). The head is three boxes on top of the neck: head (with the eyes on its sides), muzzle in front of it, and the mane down the back of the neck. In game the neck leans forward 30° and the tail hangs back 30°; the views show both straight. Both ears share one texture, and so do all four legs; the left legs are mirrored. Saddles are separate textures (equipment/horse_saddle). Before 1.21.5 the saddle and bridle were painted into the free corners of the horse texture; those pixels belong to no part here. The front legs moved 2 pixels back in 1.21.5, with the same UVs. The skeleton horse is see-through: horse_skeleton.png leaves gaps between the bones (the neck, mane and ears are empty), so its transparent base pixels are intended. Leather horse armor (leather.png, tinted with the dye color) is filled edge to edge, unused corners included.',
  },
  {
    id: 'donkey',
    title: 'Donkey and mule (64×64)',
    texture: 'entity/horse/donkey',
    size: [64, 64],
    parts: {
      head: { box: [6, 5, 7], uv: [0, 13] },
      muzzle: { box: [4, 5, 5], uv: [0, 25] },
      ear: { box: [2, 7, 1], uv: [0, 12] },
      neck: { box: [4, 12, 7], uv: [0, 35] },
      mane: { box: [2, 16, 2], uv: [56, 36], cutout: true },
      body: { box: [10, 10, 22], uv: [0, 32] },
      tail: { box: [3, 14, 4], uv: [42, 36] },
      chest: { box: [8, 8, 3], uv: [26, 21] },
      leg: { box: [4, 11, 4], uv: [48, 21] },
    },
    groups: { legs: ['leg'] },
    boxes: [
      { part: 'head', at: [-3, -7, -14] },
      { part: 'muzzle', at: [-2, -7, -19] },
      { part: 'ear', at: [-2.25, -13, -8] },
      { part: 'ear', at: [0.25, -13, -8] },
      { part: 'neck', at: [-2, -2, -14] },
      { part: 'mane', at: [-1, -7, -7] },
      { part: 'body', at: [-5, 3, -12] },
      { part: 'tail', at: [-1.5, 6, 7] },
      { part: 'chest', at: [-13, 3, 3.5] },
      { part: 'chest', at: [5, 3, 3.5] },
      ...HORSE_LEGS,
    ],
    opaque: true,
    usedBy: ['textures/entity/horse/donkey.png', 'textures/entity/horse/mule.png'],
    note: 'The horse layout with long ears and a pair of chests, drawn only when the donkey or mule carries one. Vanilla leaves the mane transparent, so donkeys and mules show none; paint it to give them one. The 2×3 horse ear still sits unused at 19,16 in donkey.png and mule.png. Both ears share one texture, and so do both chests. In game each chest hangs on a flank turned 90° about y, chest.front facing out; the views show the chests unturned beside the body, front forward. The ears lean out 15° and the neck forward 30°; the views show them straight. The left legs are mirrored. Saddles are separate textures (equipment/donkey_saddle, mule_saddle). Before 1.21.5 the saddle was painted into the free corners of the texture; those pixels belong to no part here.',
  },
  {
    id: 'llama',
    title: 'Llama (128×64)',
    texture: 'entity/llama/creamy',
    size: [128, 64],
    parts: {
      head: { box: [8, 18, 6], uv: [0, 14] },
      muzzle: { box: [4, 4, 9], uv: [0, 0] },
      ear: { box: [3, 3, 2], uv: [17, 0] },
      body: { box: [12, 18, 10], uv: [29, 0], turned: true },
      rightChest: { box: [8, 8, 3], uv: [45, 28] },
      leftChest: { box: [8, 8, 3], uv: [45, 41] },
      leg: { box: [4, 14, 4], uv: [29, 29] },
    },
    groups: { legs: ['leg'], chests: ['rightChest', 'leftChest'] },
    boxes: [
      { part: 'head', at: [-4, -9, -12] },
      { part: 'muzzle', at: [-2, -7, -16] },
      { part: 'ear', at: [-4, -12, -10] },
      { part: 'ear', at: [1, -12, -10] },
      // Legs first: their tops sit inside the body.
      { part: 'leg', at: [-5.5, 10, 4] },
      { part: 'leg', at: [1.5, 10, 4] },
      { part: 'leg', at: [-5.5, 10, -7] },
      { part: 'leg', at: [1.5, 10, -7] },
      { part: 'body', at: [-6, 2, -8] },
      { part: 'rightChest', at: [-14, 3, 0.5] },
      { part: 'leftChest', at: [6, 3, 0.5] },
    ],
    opaque: true,
    usedBy: [
      'textures/entity/llama/creamy.png (llamas and trader llamas)',
      'textures/entity/equipment/llama_body/*.png (the 16 carpets and trader_llama.png; same layout, drawn slightly larger, transparent where the wool shows)',
      'textures/entity/llama/decor/*.png in older versions (the same carpets)',
    ],
    note: 'head is one tall box for the head and the long neck, eyes near its top; muzzle juts forward from it. The body lies along the llama: body.top is its back, body.front the chest, body.back the rump. Both ears share one texture, and all four legs too (none mirrored). The chests, drawn only when the llama carries them, each have their own texture and hang on the flanks turned 90° about y: rightChest.front faces out to the right, but leftChest faces its back outward. The views show both chests unturned beside the body, front forward. In 1.21.1 the carpets were textures/entity/llama/decor/*.png, same layout.',
  },
  {
    id: 'camel',
    title: 'Camel (128×128)',
    texture: 'entity/camel/camel',
    size: [128, 128],
    parts: {
      body: { box: [15, 12, 27], uv: [0, 25] },
      hump: { box: [9, 5, 11], uv: [74, 0] },
      tail: { box: [3, 14, 0], uv: [122, 0], cutout: true },
      neck: { box: [7, 8, 19], uv: [60, 24] },
      head: { box: [7, 14, 7], uv: [21, 0] },
      muzzle: { box: [5, 5, 6], uv: [50, 0] },
      rightEar: { box: [3, 1, 2], uv: [67, 0] },
      leftEar: { box: [3, 1, 2], uv: [45, 0] },
      rightFrontLeg: { box: [5, 21, 5], uv: [0, 26] },
      leftFrontLeg: { box: [5, 21, 5], uv: [0, 0] },
      rightHindLeg: { box: [5, 21, 5], uv: [94, 16] },
      leftHindLeg: { box: [5, 21, 5], uv: [58, 16] },
    },
    groups: {
      ears: ['rightEar', 'leftEar'],
      legs: ['rightFrontLeg', 'leftFrontLeg', 'rightHindLeg', 'leftHindLeg'],
    },
    boxes: [
      // Legs first: their tops sit inside the body.
      { part: 'rightFrontLeg', at: [-7.4, 3, -13] },
      { part: 'leftFrontLeg', at: [2.4, 3, -13] },
      { part: 'rightHindLeg', at: [-7.4, 3, 7] },
      { part: 'leftHindLeg', at: [2.4, 3, 7] },
      { part: 'body', at: [-7.5, -8, -14] },
      { part: 'hump', at: [-4.5, -13, -6] },
      { part: 'tail', at: [-1.5, -5, 13] },
      { part: 'neck', at: [-3.5, -6, -25] },
      { part: 'head', at: [-3.5, -20, -25] },
      { part: 'muzzle', at: [-2.5, -20, -31] },
      { part: 'rightEar', at: [-5, -19.5, -20.5] },
      { part: 'leftEar', at: [2, -19.5, -20.5] },
    ],
    opaque: true,
    usedBy: ['textures/entity/camel/camel.png', 'camel_husk.png (1.21.11)'],
    note: 'The neck runs forward from the chest, low, and head rises from its front end like a column, eyes near the top; muzzle juts forward from the top of head. The tail is a flat strip hanging from the rump, with only a .front face (seen from behind it shows mirrored), and transparent pixels cut its outline. Every leg and each ear has its own texture. Saddles are separate textures (equipment/camel_saddle, camel_husk_saddle). Before 1.21.5 the saddle, bridle and reins were painted into the bottom half of camel.png; those pixels belong to no part here. camel_husk.png (1.21.11) uses the same model and UVs.',
  },
  {
    id: 'goat',
    title: 'Goat (64×64)',
    texture: 'entity/goat/goat',
    size: [64, 64],
    parts: {
      head: { box: [5, 7, 10], uv: [34, 46] },
      ear: { box: [3, 2, 1], uv: [2, 61] },
      horn: { box: [2, 7, 2], uv: [12, 55] },
      goatee: { box: [0, 7, 5], uv: [23, 52], cutout: true },
      coat: { box: [11, 14, 11], uv: [0, 28] },
      body: { box: [9, 11, 16], uv: [1, 1] },
      rightFrontLeg: { box: [3, 10, 3], uv: [35, 2] },
      leftFrontLeg: { box: [3, 10, 3], uv: [49, 2] },
      rightHindLeg: { box: [3, 6, 3], uv: [49, 29] },
      leftHindLeg: { box: [3, 6, 3], uv: [36, 29] },
    },
    groups: { legs: ['rightFrontLeg', 'leftFrontLeg', 'rightHindLeg', 'leftHindLeg'] },
    boxes: [
      { part: 'head', at: [-2, 2, -16] },
      { part: 'ear', at: [-5, 3, -10] },
      { part: 'ear', at: [3, 3, -10], mirror: true },
      { part: 'horn', at: [-2, -2, -10] },
      { part: 'horn', at: [1, -2, -10] },
      { part: 'goatee', at: [0.5, 11, -14] },
      // Legs first: the front legs' tops sit inside the coat.
      { part: 'rightFrontLeg', at: [-3, 14, -6] },
      { part: 'leftFrontLeg', at: [1, 14, -6] },
      { part: 'rightHindLeg', at: [-3, 18, 4] },
      { part: 'leftHindLeg', at: [1, 18, 4] },
      { part: 'coat', at: [-5, 6, -8] },
      { part: 'body', at: [-4, 7, -7] },
    ],
    opaque: true,
    usedBy: ['textures/entity/goat/goat.png (goats and screaming goats)'],
    note: 'Two boxes make the body: coat, the shaggy front half, and body, the narrower back half that runs on to the rump. The head (Java calls it nose) points down-forward at 55° in game, its .front the tip of the snout; the views show it straight out, with the goatee, a flat fin seen only from the sides, hanging under it. Both ears share one texture (the left mirrored), and so do both horns. Each leg has its own texture. A goat that lost a horn hides it; nothing changes in the texture.',
  },
  {
    id: 'panda',
    title: 'Panda (64×64)',
    texture: 'entity/panda/panda',
    size: [64, 64],
    parts: {
      head: { box: [13, 10, 9], uv: [0, 6] },
      nose: { box: [7, 5, 2], uv: [45, 16] },
      ear: { box: [5, 4, 1], uv: [52, 25] },
      body: { box: [19, 26, 13], uv: [0, 25], turned: true },
      leg: { box: [6, 9, 6], uv: [40, 0] },
    },
    groups: { legs: ['leg'] },
    boxes: [
      { part: 'head', at: [-6.5, 6.5, -21] },
      { part: 'nose', at: [-3.5, 11.5, -23] },
      { part: 'ear', at: [-8.5, 3.5, -18] },
      { part: 'ear', at: [3.5, 3.5, -18] },
      // Legs first: their tops sit inside the body.
      { part: 'leg', at: [-8.5, 15, 6] },
      { part: 'leg', at: [2.5, 15, 6] },
      { part: 'leg', at: [-8.5, 15, -12] },
      { part: 'leg', at: [2.5, 15, -12] },
      { part: 'body', at: [-9.5, 3.5, -13] },
    ],
    opaque: true,
    usedBy: ['textures/entity/panda/panda.png', 'lazy_panda.png, worried_panda.png, playful_panda.png, brown_panda.png, weak_panda.png, aggressive_panda.png (the personality variants)'],
    note: 'The body lies along the panda: body.top is its back, body.front the chest, body.back the rump. The nose covers the bottom half of head.front. Both ears share one texture, and all four legs too (none mirrored). Sitting, rolling and lying are animations; the texture stays the same.',
  },
  {
    id: 'polar_bear',
    title: 'Polar bear (128×64)',
    texture: 'entity/bear/polarbear',
    size: [128, 64],
    parts: {
      head: { box: [7, 7, 7], uv: [0, 0] },
      mouth: { box: [5, 3, 3], uv: [0, 44] },
      ear: { box: [2, 2, 1], uv: [26, 0] },
      shoulders: { box: [12, 12, 10], uv: [39, 0], turned: true },
      body: { box: [14, 14, 11], uv: [0, 19], turned: true },
      frontLeg: { box: [4, 10, 6], uv: [50, 40] },
      hindLeg: { box: [4, 10, 8], uv: [50, 22] },
    },
    groups: { legs: ['frontLeg', 'hindLeg'] },
    boxes: [
      { part: 'head', at: [-3.5, 7, -19] },
      { part: 'mouth', at: [-2.5, 11, -22] },
      { part: 'ear', at: [-4.5, 6, -17] },
      { part: 'ear', at: [2.5, 6, -17], mirror: true },
      // Legs first: their tops sit inside the body.
      { part: 'frontLeg', at: [-5.5, 14, -10] },
      { part: 'frontLeg', at: [1.5, 14, -10] },
      { part: 'hindLeg', at: [-6.5, 14, 4] },
      { part: 'hindLeg', at: [2.5, 14, 4] },
      { part: 'shoulders', at: [-6, 6, -13] },
      { part: 'body', at: [-7, 5, -1] },
    ],
    opaque: true,
    usedBy: ['textures/entity/bear/polarbear.png'],
    note: 'Two lying boxes make the body: shoulders, the front half, and body, the wider back half; for both, .top is the bear\'s back and .bottom its belly. The mouth juts from the bottom of head.front. Both ears share one texture; the left one is mirrored since 1.21.11 (before, both drew it the same way). Both front legs share one texture, and both hind legs another. Standing up on its hind legs is an animation; the views show the bear on all fours.',
  },
];

const LARGE_ANIMALS_ALIASES: Record<string, string> = {
  zombie_horse: 'horse',
  skeleton_horse: 'horse',
  horse_armor: 'horse',
  mule: 'donkey',
  trader_llama: 'llama',
  llama_decor: 'llama',
  camel_husk: 'camel',
  polarbear: 'polar_bear',
};

// ---- Monsters -------------------------------------------------------------------------------


/** Ghast tentacle feet: [x, z] of each pivot (Java PartPose.offset), 3 rows of 3. */
const TENTACLES: [number, number][] = [
  [-3.75, -5], [1.25, -5], [6.25, -5],
  [-6.25, 0], [-1.25, 0], [3.75, 0],
  [-3.75, 5], [1.25, 5], [6.25, 5],
];

/** Blaze rods at rest (createBodyLayer): three rings around the head and under it. */
const BLAZE_RODS: [number, number, number][] = [
  [9, -1, 0], [4.86, -1.12, 7.57], [-3.75, -1.46, 8.18], [-8.91, -1.93, 1.27],
  [4.95, 1.58, 4.95], [-1.49, 1.2, 6.84], [-6.56, 1.01, 2.44], [-5.6, 1.06, -4.2],
  [4.46, 11.96, 2.27], [0.5, 11.89, 4.98], [-3.92, 11.35, 3.11], [-4.73, 10.61, -1.62],
];

const MONSTERS: LayoutDef[] = [
  {
    id: 'slime',
    title: 'Slime (64×32)',
    texture: 'entity/slime/slime',
    size: [64, 32],
    parts: {
      outerCube: { box: [8, 8, 8], uv: [0, 0] },
      innerCube: { box: [6, 6, 6], uv: [0, 16] },
      rightEye: { box: [2, 2, 2], uv: [32, 0] },
      leftEye: { box: [2, 2, 2], uv: [32, 4] },
      mouth: { box: [1, 1, 1], uv: [32, 8] },
    },
    groups: { eyes: ['rightEye', 'leftEye'], face: ['rightEye', 'leftEye', 'mouth'] },
    boxes: [
      { part: 'innerCube', at: [-3, 17, -3] },
      { part: 'rightEye', at: [-3.25, 18, -3.5] },
      { part: 'leftEye', at: [1.25, 18, -3.5] },
      { part: 'mouth', at: [0, 21, -3.5] },
      { part: 'outerCube', at: [-4, 16, -4] },
    ],
    usedBy: ['textures/entity/slime/slime.png'],
    note: 'Two cubes from one texture: the game draws outerCube translucent around an opaque innerCube that carries the eyes and the mouth. Keep outerCube semi-transparent (vanilla alpha is about 50%) so the face shows through; the eyes and the mouth stick half a pixel out of innerCube.front. The magma cube has its own layout, magma_cube.',
  },
  {
    id: 'magma_cube',
    title: 'Magma cube (64×64)',
    texture: 'entity/slime/magmacube',
    size: [64, 64],
    parts: {
      segment0: { box: [8, 1, 8], uv: [0, 0] },
      segment1: { box: [8, 1, 8], uv: [0, 9] },
      segment2: { box: [8, 1, 8], uv: [0, 18] },
      segment3: { box: [8, 1, 8], uv: [0, 27] },
      segment4: { box: [8, 1, 8], uv: [32, 0] },
      segment5: { box: [8, 1, 8], uv: [32, 9] },
      segment6: { box: [8, 1, 8], uv: [32, 18] },
      segment7: { box: [8, 1, 8], uv: [32, 27] },
      insideCube: { box: [4, 4, 4], uv: [24, 40] },
    },
    groups: { segments: ['segment0', 'segment1', 'segment2', 'segment3', 'segment4', 'segment5', 'segment6', 'segment7'] },
    boxes: [
      { part: 'insideCube', at: [-2, 18, -2] },
      ...[0, 1, 2, 3, 4, 5, 6, 7].map((i): BoxDef => ({ part: `segment${i}`, at: [-4, 16 + i, -4] })),
    ],
    opaque: true,
    usedBy: ['textures/entity/slime/magmacube.png (1.21.5+)'],
    note: 'The cube is eight stacked slices, segment0 at the top to segment7 at the bottom, each 1 pixel high with its own texture: their .front rows together make the face (the eyes sit on segment2 and segment3). Only segment0.top and segment7.bottom show when the cube is still; the other tops and bottoms show when it jumps and the slices spread apart, revealing insideCube, the glowing core. Before 1.21.5 magmacube.png was 64×32 with other UVs (slices sharing texture rows); this layout does not fit it.',
  },
  {
    id: 'blaze',
    title: 'Blaze (64×32)',
    texture: 'entity/blaze',
    size: [64, 32],
    parts: { head: { box: [8, 8, 8], uv: [0, 0] }, rod: { box: [2, 8, 2], uv: [0, 16] } },
    groups: { rods: ['rod'] },
    boxes: [{ part: 'head', at: [-4, -4, -4] }, ...BLAZE_RODS.map((at): BoxDef => ({ part: 'rod', at }))],
    opaque: true,
    usedBy: ['textures/entity/blaze.png'],
    note: 'All twelve rods share one texture. They circle the head in three rings (four at its level, four lower, four under it) and spin in game; the views show them at their resting places.',
  },
  {
    id: 'ghast',
    title: 'Ghast (128×64)',
    texture: 'entity/ghast/ghast',
    size: [128, 64],
    parts: { body: { box: [32, 32, 32], uv: [0, 0] }, tentacle: { box: [4, 24, 4], uv: [0, 0] } },
    groups: { tentacles: ['tentacle'] },
    boxes: [
      { part: 'body', at: [-16, 19.2, -16] },
      ...TENTACLES.map(([x, z]): BoxDef => ({ part: 'tentacle', at: [(x - 1) * 2, 49.2, (z - 1) * 2] })),
    ],
    opaque: true,
    usedBy: ['textures/entity/ghast/ghast.png', 'ghast_shooting.png (the face with the mouth open)', 'ghast.png and ghast_shooting.png before 1.21.6 (64×32: the same UVs at half the resolution; the game fits any 2:1 texture to the model, so a 128×64 one works there too)'],
    note: 'Since 1.21.6 the ghast texture is twice the resolution of its model, so this layout counts texture pixels: a 32-pixel cube and 4-pixel-wide tentacles. All nine tentacles share one texture in the unused top-left corner; in game they are 18 to 24 pixels long, cut from the top of it, and the views draw them all 24 long.',
  },
  {
    id: 'happy_ghast',
    title: 'Happy ghast (128×128)',
    texture: 'entity/ghast/happy_ghast',
    size: [128, 128],
    parts: { body: { box: [32, 32, 32], uv: [0, 0] }, tentacle: { box: [4, 16, 4], uv: [0, 0] } },
    groups: { tentacles: ['tentacle'] },
    boxes: [
      { part: 'body', at: [-16, 16, -16] },
      ...TENTACLES.map(([x, z]): BoxDef => ({ part: 'tentacle', at: [(x - 1) * 2, 46, (z - 1) * 2] })),
    ],
    opaque: true,
    usedBy: ['textures/entity/ghast/happy_ghast.png', 'happy_ghast_ropes.png (the leash ropes drawn a little larger than the body when it is harnessed and leashed; transparent elsewhere)'],
    note: 'The grown happy ghast (1.21.6+). Its texture is twice the resolution of its model, so this layout counts texture pixels: a 32-pixel cube and 4-pixel-wide tentacles. All nine tentacles share one texture in the unused top-left corner; in game they are 8 to 16 pixels long, cut from the top of it, and the views draw them all 16 long. The ghastling (baby) has its own layout, happy_ghast_baby; the harness another, happy_ghast_harness.',
  },
  {
    id: 'happy_ghast_baby',
    title: 'Ghastling (64×64)',
    texture: 'entity/ghast/happy_ghast_baby',
    size: [64, 64],
    parts: {
      body: { box: [16, 16, 16], uv: [0, 0] },
      innerBody: { box: [16, 16, 16], uv: [0, 32] },
      tentacle: { box: [2, 8, 2], uv: [0, 0] },
    },
    groups: { tentacles: ['tentacle'] },
    boxes: [
      { part: 'innerBody', at: [-8, 8, -8] },
      { part: 'body', at: [-8, 8, -8] },
      ...TENTACLES.map(([x, z]): BoxDef => ({ part: 'tentacle', at: [x - 1, 23, z - 1] })),
    ],
    usedBy: ['textures/entity/ghast/happy_ghast_baby.png'],
    note: 'The ghastling, the baby happy ghast (1.21.6+), at the model\'s own resolution. body carries the face; innerBody is a second cube inside it, half a pixel smaller, that only shows through pixels left transparent in body (vanilla paints body opaque and innerBody pink). All nine tentacles share one texture in the unused top-left corner; in game they are 4 to 8 pixels long, cut from the top of it, and the views draw them all 8 long.',
  },
  {
    id: 'happy_ghast_harness',
    title: 'Happy ghast harness (128×128)',
    texture: 'entity/equipment/happy_ghast_body/white_harness',
    size: [128, 128],
    parts: { harness: { box: [32, 32, 32], uv: [0, 0] }, goggles: { box: [32, 10, 10], uv: [0, 64] } },
    boxes: [
      { part: 'harness', at: [-16, 16, -16] },
      { part: 'goggles', at: [-16, 23, -16] },
    ],
    usedBy: ['textures/entity/equipment/happy_ghast_body/{color}_harness.png (16 dye colors)'],
    note: 'The harness worn by a happy ghast (1.21.6+), at twice the resolution of its model like happy_ghast. harness wraps the whole cube; leave it transparent where the ghast should show. goggles is a bar across the face, drawn slightly larger; the views show it lowered over the eyes, as when the ghast is ridden; otherwise it is raised and tilted 45° up.',
  },
  {
    id: 'phantom',
    title: 'Phantom (64×64)',
    texture: 'entity/phantom',
    topView: true,
    size: [64, 64],
    parts: {
      head: { box: [7, 3, 5], uv: [0, 0] },
      body: { box: [5, 3, 9], uv: [0, 8] },
      tailBase: { box: [3, 2, 6], uv: [3, 20] },
      tailTip: { box: [1, 1, 6], uv: [4, 29] },
      wingBase: { box: [6, 2, 9], uv: [23, 12] },
      wingTip: { box: [13, 1, 9], uv: [16, 24], cutout: true },
    },
    groups: { wings: ['wingBase', 'wingTip'], tail: ['tailBase', 'tailTip'] },
    boxes: [
      { part: 'head', at: [-4, -1, -12] },
      { part: 'body', at: [-3, -2, -8] },
      { part: 'tailBase', at: [-2, -2, 1] },
      { part: 'tailTip', at: [-1, -1.5, 7] },
      { part: 'wingBase', at: [-9, -2, -8], mirror: true },
      { part: 'wingTip', at: [-22, -2, -8], mirror: true },
      { part: 'wingBase', at: [2, -2, -8] },
      { part: 'wingTip', at: [8, -2, -8] },
    ],
    opaque: true,
    usedBy: ['textures/entity/phantom.png', 'phantom_eyes.png (glowing eyes, same layout, transparent elsewhere)'],
    note: 'The phantom flies flat, so its boxes are already horizontal: wingBase.top and wingTip.top are the upper side of the wings, .bottom the underside, and the views see the wings edge-on. Both wings share one texture; the right one is mirrored. Transparent pixels cut the ragged outline of the wing tips. The head is 7 wide and the body 5, both off center by half a pixel in game. In game the head tilts down a little, the body tips up and the wings flap; the views show them straight.',
  },
  {
    id: 'guardian',
    title: 'Guardian and elder guardian (64×64)',
    texture: 'entity/guardian',
    size: [64, 64],
    parts: {
      body: { box: [12, 12, 16], uv: [0, 0] },
      side: { box: [2, 12, 12], uv: [0, 28] },
      plate: { box: [12, 2, 12], uv: [16, 40] },
      eye: { box: [2, 2, 1], uv: [8, 0] },
      spike: { box: [2, 9, 2], uv: [0, 0] },
      tail0: { box: [4, 4, 8], uv: [40, 0] },
      tail1: { box: [3, 3, 7], uv: [0, 54] },
      tail2: { box: [2, 2, 6], uv: [41, 32] },
      fin: { box: [1, 9, 9], uv: [25, 19], cutout: true, shared: true },
    },
    groups: { tail: ['tail0', 'tail1', 'tail2', 'fin'], spikes: ['spike'] },
    boxes: [
      { part: 'body', at: [-6, 10, -8] },
      { part: 'side', at: [-8, 10, -6] },
      { part: 'side', at: [6, 10, -6], mirror: true },
      { part: 'plate', at: [-6, 8, -6] },
      { part: 'plate', at: [-6, 22, -6] },
      { part: 'eye', at: [-1, 15, -8.25] },
      { part: 'tail0', at: [-2, 14, 7] },
      { part: 'tail1', at: [-1.5, 14.5, 14] },
      { part: 'tail2', at: [-1, 15, 20] },
      { part: 'fin', at: [0, 11.5, 23] },
    ],
    usedBy: ['textures/entity/guardian.png', 'textures/entity/guardian_elder.png (the elder guardian is the same model scaled up)'],
    note: 'The body is a 12×12×16 box with a 2-pixel side panel on each flank (the left one mirrored) and a plate on top and bottom (one texture for both), so it reads as a rounded block. The eye is a separate 2×2 box set into the middle of body.front. The tail is three boxes getting thinner toward the back, with a fin standing up at the end. Vanilla paints only what shows: the strips of body.top, .bottom, .right and .left that the panels and plates leave uncovered, side.right (the left panel shows it mirrored) and fin.right (the game draws the fin from both sides); the rest is transparent and hidden, so the base need not be opaque. The fin\'s 1-pixel top and bottom edges share texture pixels with body.left, as in vanilla. The twelve spikes share one texture in body\'s unused top-left corner; in game they stick out diagonally from the edges, so the views leave them out.',
  },
  {
    id: 'shulker',
    title: 'Shulker (64×64)',
    texture: 'entity/shulker/shulker',
    size: [64, 64],
    parts: {
      lid: { box: [16, 12, 16], uv: [0, 0] },
      base: { box: [16, 8, 16], uv: [0, 28] },
      head: { box: [6, 6, 6], uv: [0, 52] },
    },
    groups: { shell: ['lid', 'base'] },
    boxes: [
      { part: 'base', at: [-8, 16, -8] },
      { part: 'head', at: [-3, 12, -3] },
      { part: 'lid', at: [-8, 0, -8] },
    ],
    usedBy: ['textures/entity/shulker/shulker.png and shulker_{color}.png (16 dye colors)', 'the shulker box block (same texture: lid and base only)'],
    note: 'The shell is two boxes: lid over base. Closed, the lid comes down to y 8, overlapping the base and hiding the head. The views show it half open, as when the shulker peeks, so the head shows between them. The two interlock: vanilla leaves an 8×4 notch transparent at the bottom middle of each side of the lid, and the top corners of each side of the base, so the base\'s raised middle fills the lid\'s notch when it closes. lid.bottom (the inside of the lid) and base.top (the floor of the shell) are transparent but for a rim.',
  },
  {
    id: 'strider',
    title: 'Strider (64×128)',
    texture: 'entity/strider/strider',
    size: [64, 128],
    parts: {
      body: { box: [16, 14, 16], uv: [0, 0] },
      rightLeg: { box: [4, 16, 4], uv: [0, 32] },
      leftLeg: { box: [4, 16, 4], uv: [0, 55] },
      topBristle: { box: [12, 16, 0], uv: [32, 33], cutout: true },
      topBristleInner: { box: [12, 16, 0], uv: [44, 33], cutout: true },
      middleBristle: { box: [12, 16, 0], uv: [32, 49], cutout: true },
      middleBristleInner: { box: [12, 16, 0], uv: [44, 49], cutout: true },
      bottomBristle: { box: [12, 16, 0], uv: [32, 65], cutout: true },
      bottomBristleInner: { box: [12, 16, 0], uv: [44, 65], cutout: true },
    },
    groups: {
      legs: ['rightLeg', 'leftLeg'],
      bristles: ['topBristle', 'topBristleInner', 'middleBristle', 'middleBristleInner', 'bottomBristle', 'bottomBristleInner'],
    },
    boxes: [
      { part: 'rightLeg', at: [-6, 8, -2] },
      { part: 'leftLeg', at: [2, 8, -2] },
      { part: 'body', at: [-8, -5, -8] },
    ],
    opaque: true,
    usedBy: [
      'textures/entity/strider/strider.png',
      'strider_cold.png (the shivering strider out of lava)',
      'textures/entity/equipment/strider_saddle/saddle.png (1.21.5+; textures/entity/strider/strider_saddle.png before), the saddle in the same layout, transparent elsewhere',
    ],
    note: 'Three tiers of bristles hang from each side of the body, both sides sharing a texture (the right side mirrored). Each tier is a flat 12×16 sheet with two faces: topBristle is the outer side and topBristleInner the side toward the body; column 0 is the edge on the body, row 0 the back end. Transparent pixels cut each bristle\'s outline; vanilla leaves the Inner faces transparent, since the game draws the outer face from both sides. They hang 50° to 70° from the body and sway, so the views leave them out.',
  },
  {
    id: 'warden',
    title: 'Warden (128×128)',
    texture: 'entity/warden/warden',
    size: [128, 128],
    parts: {
      head: { box: [16, 16, 10], uv: [0, 32] },
      rightTendril: { box: [16, 16, 0], uv: [52, 32], cutout: true },
      leftTendril: { box: [16, 16, 0], uv: [58, 0], cutout: true },
      body: { box: [18, 21, 11], uv: [0, 0] },
      ribcage: { box: [9, 21, 0], uv: [90, 11], cutout: true },
      rightArm: { box: [8, 28, 8], uv: [44, 50] },
      leftArm: { box: [8, 28, 8], uv: [0, 58] },
      rightLeg: { box: [6, 13, 6], uv: [76, 48] },
      leftLeg: { box: [6, 13, 6], uv: [76, 76] },
    },
    groups: {
      tendrils: ['rightTendril', 'leftTendril'],
      arms: ['rightArm', 'leftArm'],
      legs: ['rightLeg', 'leftLeg'],
      limbs: ['rightArm', 'leftArm', 'rightLeg', 'leftLeg'],
    },
    boxes: [
      { part: 'head', at: [-8, -26, -5] },
      { part: 'rightTendril', at: [-24, -35, 0] },
      { part: 'leftTendril', at: [8, -35, 0] },
      { part: 'body', at: [-9, -10, -4] },
      { part: 'ribcage', at: [-9, -10, -4.1] },
      { part: 'ribcage', at: [0, -10, -4.1], mirror: true },
      { part: 'rightArm', at: [-17, -10, -3] },
      { part: 'leftArm', at: [9, -10, -3] },
      { part: 'rightLeg', at: [-9, 11, -3] },
      { part: 'leftLeg', at: [3, 11, -3] },
    ],
    opaque: true,
    usedBy: [
      'textures/entity/warden/warden.png',
      'warden_bioluminescent_layer.png, warden_heart.png, warden_pulsating_spots_1.png and _2.png (glowing layers in the same layout, transparent elsewhere: the heart on body, the spots on body, head and limbs)',
    ],
    note: 'The ribcage is a flat sheet over body.front, one texture for both halves (the left one mirrored), with gaps that show the chest (and the heart) behind it. The tendrils are flat sheets on both sides of the head, each with its own texture, standing out sideways from the middle of the head; the side views see them edge-on. Their transparent pixels cut their outline.',
  },
];

const MONSTERS_ALIASES: Record<string, string> = {
  magmacube: 'magma_cube',
  ghast_shooting: 'ghast',
  happy_ghast_ropes: 'happy_ghast',
  ghastling: 'happy_ghast_baby',
  phantom_eyes: 'phantom',
  elder_guardian: 'guardian',
  guardian_elder: 'guardian',
  shulker_box: 'shulker',
  strider_cold: 'strider',
  strider_saddle: 'strider',
};

// ---- Illagers, golems and other figures -----------------------------------------------------


const HUMANOIDS: LayoutDef[] = [
  {
    id: 'illager',
    title: 'Illager (64×64)',
    texture: 'entity/illager/vindicator',
    size: [64, 64],
    parts: {
      head: { box: [8, 10, 8], uv: [0, 0] },
      hat: { box: [8, 12, 8], uv: [32, 0] },
      nose: { box: [2, 4, 2], uv: [24, 0] },
      body: { box: [8, 12, 6], uv: [16, 20] },
      jacket: { box: [8, 20, 6], uv: [0, 38] },
      freeArm: { box: [4, 12, 4], uv: [40, 46] },
      arm: { box: [4, 8, 4], uv: [44, 22] },
      armsMiddle: { box: [8, 4, 4], uv: [40, 38] },
      leg: { box: [4, 12, 4], uv: [0, 22] },
    },
    groups: { arms: ['freeArm', 'arm', 'armsMiddle'], crossedArms: ['arm', 'armsMiddle'], legs: ['leg'] },
    boxes: [
      { part: 'head', at: [-4, -10, -4] },
      { part: 'hat', at: [-4, -10, -4] },
      { part: 'nose', at: [-1, -3, -6] },
      { part: 'body', at: [-4, 0, -3] },
      { part: 'jacket', at: [-4, 0, -3] },
      { part: 'leg', at: [-4, 12, -2] },
      { part: 'leg', at: [0, 12, -2], mirror: true },
      { part: 'freeArm', at: [-8, 0, -2] },
      { part: 'freeArm', at: [4, 0, -2], mirror: true },
    ],
    character: true,
    usedBy: [
      'textures/entity/illager/vindicator.png',
      'evoker.png',
      'pillager.png',
      'illusioner.png',
    ],
    note: 'A villager body (robe on jacket) with two sets of arms in one texture. freeArm is the pair that hangs at the sides, swings a weapon or casts spells (the pillager always uses it); arm and armsMiddle are the crossed arms vindicators, evokers and illusioners fold while idle, and the pillager leaves them transparent. Only one set shows at a time, so the views draw the hanging arms and the crossed ones have no box. hat is a hood over the head, 12 pixels tall and drawn slightly larger than it; only the illusioner paints it. Both legs share one texture, and so do both free arms; the left ones are mirrored. The nose covers rows 7–9 of head.front and hangs one pixel below the chin.',
  },
  {
    id: 'armor_stand',
    title: 'Armor stand (64×64)',
    texture: 'entity/armorstand/wood',
    size: [64, 64],
    parts: {
      head: { box: [2, 7, 2], uv: [0, 0] },
      body: { box: [12, 3, 3], uv: [0, 26] },
      rightArm: { box: [2, 12, 2], uv: [24, 0] },
      leftArm: { box: [2, 12, 2], uv: [32, 16] },
      rightBodyStick: { box: [2, 7, 2], uv: [16, 0] },
      leftBodyStick: { box: [2, 7, 2], uv: [48, 16] },
      hip: { box: [8, 2, 2], uv: [0, 48] },
      rightLeg: { box: [2, 11, 2], uv: [8, 0] },
      leftLeg: { box: [2, 11, 2], uv: [40, 16] },
      basePlate: { box: [12, 1, 12], uv: [0, 32] },
    },
    groups: {
      arms: ['rightArm', 'leftArm'],
      legs: ['rightLeg', 'leftLeg'],
      limbs: ['rightArm', 'leftArm', 'rightLeg', 'leftLeg'],
      sticks: ['rightBodyStick', 'leftBodyStick'],
    },
    boxes: [
      { part: 'head', at: [-1, -6, -1] },
      { part: 'body', at: [-6, 0, -1.5] },
      { part: 'rightArm', at: [-7, 0, -1] },
      { part: 'leftArm', at: [5, 0, -1], mirror: true },
      { part: 'rightBodyStick', at: [-3, 3, -1] },
      { part: 'leftBodyStick', at: [1, 3, -1] },
      { part: 'hip', at: [-4, 10, -1] },
      { part: 'rightLeg', at: [-2.9, 12, -1] },
      { part: 'leftLeg', at: [0.9, 12, -1], mirror: true },
      { part: 'basePlate', at: [-6, 23, -6] },
    ],
    opaque: true,
    usedBy: ['textures/entity/armorstand/wood.png'],
    note: 'head is the neck stick an equipped helmet or head sits on, and body the shoulder bar. Every stick has its own texture; the left arm and leg are drawn mirrored like vanilla left limbs. The arms show only when the stand has them, and basePlate only when it has one. The names along the bottom of the vanilla texture are an easter egg the model never draws. In game the body half-pixel and the legs a tenth of a pixel off the grid; the views snap to whole pixels.',
  },
  {
    id: 'snow_golem',
    title: 'Snow golem (64×64)',
    texture: 'entity/snow_golem',
    size: [64, 64],
    parts: {
      head: { box: [8, 8, 8], uv: [0, 0] },
      upperBody: { box: [10, 10, 10], uv: [0, 16] },
      lowerBody: { box: [12, 12, 12], uv: [0, 36] },
      arm: { box: [12, 2, 2], uv: [32, 0] },
    },
    groups: { body: ['upperBody', 'lowerBody'], arms: ['arm'] },
    boxes: [
      { part: 'head', at: [-4, -5, -4] },
      { part: 'upperBody', at: [-5, 3, -5] },
      { part: 'lowerBody', at: [-6, 13, -6] },
      { part: 'arm', at: [-16, 6, -2] },
      { part: 'arm', at: [4, 6, 0] },
    ],
    opaque: true,
    usedBy: ['textures/entity/snow_golem.png'],
    note: 'Three stacked snowballs and two stick arms that share one texture. Every box is drawn half a pixel smaller on each side in game, so the snowballs just touch; the views stack them whole, the head one pixel higher and the lower body one pixel lower than the Java boxes. In game the arms angle up about 57° and the right one is the same stick turned end for end; the views show both straight out to the sides. The carved pumpkin is a block drawn over the head, not part of this texture: head.front is the face under it, seen once the golem is sheared.',
  },
  {
    id: 'allay',
    title: 'Allay (32×32)',
    texture: 'entity/allay/allay',
    size: [32, 32],
    parts: {
      head: { box: [5, 5, 5], uv: [0, 0] },
      body: { box: [3, 4, 2], uv: [0, 10] },
      lowerBody: { box: [3, 5, 2], uv: [0, 16] },
      rightArm: { box: [1, 4, 2], uv: [23, 0] },
      leftArm: { box: [1, 4, 2], uv: [23, 6] },
      wing: { box: [0, 5, 8], uv: [16, 14], cutout: true },
    },
    groups: { arms: ['rightArm', 'leftArm'], wings: ['wing'] },
    boxes: [
      { part: 'head', at: [-2.5, 14.5, -2.5] },
      { part: 'rightArm', at: [-2.5, 19.5, -1] },
      { part: 'leftArm', at: [1.5, 19.5, -1] },
      { part: 'lowerBody', at: [-1.5, 19.5, -1] },
      { part: 'body', at: [-1.5, 19.5, -1] },
      { part: 'wing', at: [-0.5, 20.5, 0.6] },
      { part: 'wing', at: [0.5, 20.5, 0.6] },
    ],
    usedBy: ['textures/entity/allay/allay.png'],
    note: 'The allay is drawn translucent, so partly transparent pixels are part of the design. lowerBody is a second, longer box over the body, drawn slightly smaller: the wispy lower half. Each arm has its own texture. Both wings share one texture and are flat planes with only .right and .left faces (vanilla paints only wing.right; the game draws it double-sided, so it shows from both sides); transparent pixels cut their outline. In game the wings spread out and back and the arms swing; the views show them folded straight behind the body and snap the half-pixel offsets to the grid. Not the vex layout: the vex has wider arms, a lower lowerBody and a mirrored left wing.',
  },
  {
    id: 'vex',
    title: 'Vex (32×32)',
    texture: 'entity/illager/vex',
    size: [32, 32],
    parts: {
      head: { box: [5, 5, 5], uv: [0, 0] },
      body: { box: [3, 4, 2], uv: [0, 10] },
      lowerBody: { box: [3, 5, 2], uv: [0, 16] },
      rightArm: { box: [2, 4, 2], uv: [23, 0] },
      leftArm: { box: [2, 4, 2], uv: [23, 6] },
      wing: { box: [0, 5, 8], uv: [16, 14], cutout: true },
    },
    groups: { arms: ['rightArm', 'leftArm'], wings: ['wing'] },
    boxes: [
      { part: 'head', at: [-2.5, 12.5, -2.5] },
      { part: 'rightArm', at: [-3, 17.25, -1] },
      { part: 'leftArm', at: [1, 17.25, -1] },
      { part: 'lowerBody', at: [-1.5, 18.5, -1] },
      { part: 'body', at: [-1.5, 17.5, -1] },
      { part: 'wing', at: [-0.5, 18.5, 1] },
      { part: 'wing', at: [0.5, 18.5, 1], mirror: true },
    ],
    usedBy: ['textures/entity/illager/vex.png', 'vex_charging.png (same layout, used while it attacks)'],
    note: 'The vex is drawn translucent, so partly transparent pixels are part of the design. lowerBody is a second, longer box hanging one pixel lower than the body, drawn slightly smaller: the wispy tail. Each arm has its own texture and sinks half a pixel into the body. Both wings share one texture, the left one mirrored; they are flat planes with only .right and .left faces (vanilla paints only wing.right; the game draws it double-sided, so it shows from both sides), and transparent pixels cut their outline. In game the wings spread out and flap; the views show them folded straight behind the body and snap the half-pixel offsets to the grid.',
  },
  {
    id: 'squid',
    title: 'Squid (64×32)',
    texture: 'entity/squid/squid',
    size: [64, 32],
    parts: {
      body: { box: [12, 16, 12], uv: [0, 0] },
      tentacle: { box: [2, 18, 2], uv: [48, 0] },
    },
    groups: { tentacles: ['tentacle'] },
    boxes: [
      // Tentacles first: their tops sit inside the body.
      ...([[4, -1], [2.54, 2.54], [-1, 4], [-4.54, 2.54], [-6, -1], [-4.54, -4.54], [-1, -6], [2.54, -4.54]] as const).map(
        ([x, z]): BoxDef => ({ part: 'tentacle', at: [x, 15, z] }),
      ),
      { part: 'body', at: [-6, 0, -6] },
    ],
    opaque: true,
    usedBy: ['textures/entity/squid/squid.png', 'squid/glow_squid.png (same layout)'],
    note: 'The body points up with the tentacles hanging from its bottom in a ring; all eight share one texture. In game each tentacle is turned to face out from the center and they sway together; the views show them straight down, unturned and snapped to the grid.',
  },
  {
    id: 'dolphin',
    title: 'Dolphin (64×64)',
    texture: 'entity/dolphin',
    size: [64, 64],
    parts: {
      head: { box: [8, 7, 6], uv: [0, 0] },
      nose: { box: [2, 2, 4], uv: [0, 13] },
      body: { box: [8, 7, 13], uv: [22, 0] },
      backFin: { box: [1, 4, 5], uv: [51, 0], turned: true },
      fin: { box: [1, 4, 7], uv: [48, 20] },
      tail: { box: [4, 5, 11], uv: [0, 19] },
      tailFin: { box: [10, 1, 6], uv: [19, 20] },
    },
    groups: { fins: ['backFin', 'fin', 'tailFin'] },
    boxes: [
      { part: 'head', at: [-4, 15, -11] },
      { part: 'nose', at: [-1, 20, -15] },
      { part: 'body', at: [-4, 15, -5] },
      { part: 'backFin', at: [-0.5, 10, -1] },
      { part: 'fin', at: [-2.5, 22, -1] },
      { part: 'fin', at: [1.5, 22, -1], mirror: true },
      { part: 'tail', at: [-2, 17, 6] },
      { part: 'tailFin', at: [-5, 19, 15] },
    ],
    opaque: true,
    usedBy: ['textures/entity/dolphin.png'],
    note: 'The dolphin swims along z: body.front faces forward, the head and nose stick out in front, the tail and its flat tail fin trail behind. In game the back fin leans back 60°; the views stand it up on the back like a lying part (backFin.top is its tip). The two side fins share one texture, the left one mirrored; in game they splay out and down from the belly, and the views hang them straight down under it. The tail tilts slightly; the views show it straight.',
  },
  {
    id: 'copper_golem',
    title: 'Copper golem (64×64)',
    texture: 'entity/copper_golem/copper_golem',
    size: [64, 64],
    parts: {
      head: { box: [8, 5, 10], uv: [0, 0] },
      nose: { box: [2, 3, 2], uv: [56, 0] },
      antenna: { box: [2, 4, 2], uv: [37, 8] },
      antennaTip: { box: [4, 4, 4], uv: [37, 0] },
      body: { box: [8, 6, 6], uv: [0, 15] },
      rightArm: { box: [3, 10, 4], uv: [36, 16] },
      leftArm: { box: [3, 10, 4], uv: [50, 16] },
      rightLeg: { box: [4, 5, 4], uv: [0, 27] },
      leftLeg: { box: [4, 5, 4], uv: [16, 27] },
    },
    groups: { arms: ['rightArm', 'leftArm'], legs: ['rightLeg', 'leftLeg'], limbs: ['rightArm', 'leftArm', 'rightLeg', 'leftLeg'], antennas: ['antenna', 'antennaTip'] },
    boxes: [
      { part: 'head', at: [-4, 8, -5] },
      { part: 'nose', at: [-1, 11, -6] },
      { part: 'antenna', at: [-1, 4, -1] },
      { part: 'antennaTip', at: [-2, 0, -2] },
      { part: 'body', at: [-4, 13, -3] },
      { part: 'rightArm', at: [-7, 12, -2] },
      { part: 'leftArm', at: [4, 12, -2] },
      { part: 'rightLeg', at: [-4, 19, -2] },
      { part: 'leftLeg', at: [0, 19, -2] },
    ],
    opaque: true,
    usedBy: [
      'textures/entity/copper_golem/copper_golem.png, exposed_copper_golem.png, weathered_copper_golem.png, oxidized_copper_golem.png',
      'copper_golem_eyes.png and the other _eyes files (glowing eyes, same layout, transparent elsewhere)',
    ],
    note: 'Exists only from 1.21.10. A wide, flat head with the nose on rows 1–3 of head.front and an antenna on top: a rod (antenna) and a knob (antennaTip). Every limb has its own texture, none mirrored.',
  },
];

const HUMANOIDS_ALIASES: Record<string, string> = {
  vindicator: 'illager',
  evoker: 'illager',
  pillager: 'illager',
  illusioner: 'illager',
  vex_charging: 'vex',
  glow_squid: 'squid',
  exposed_copper_golem: 'copper_golem',
  weathered_copper_golem: 'copper_golem',
  oxidized_copper_golem: 'copper_golem',
  wandering_trader: 'villager',
  wolf_armor: 'wolf',
};

export const MOB_LAYOUTS: LayoutDef[] = [...SMALL_ANIMALS, ...LARGE_ANIMALS, ...MONSTERS, ...HUMANOIDS];
export const MOB_ALIASES: Record<string, string> = { ...SMALL_ANIMALS_ALIASES, ...LARGE_ANIMALS_ALIASES, ...MONSTERS_ALIASES, ...HUMANOIDS_ALIASES };
